### ISSUE TITLE
Error Inesperado

### ISSUE THREAD

**Issue by gsilval** [Destripador/Herramientas-SIPRED-dictamen-fiscal#1]
Al intentar hacer la conversión utilizando Office Professional Plus 2019, presenta un mensaje de "Error Inesperado" y no es posible hacer la conversión.
![Error](https://user-images.githubusercontent.com/43453319/90032569-1f786880-dc84-11ea-95f5-e63248529501.png)

**Comment by Destripador** [comment]
check new version
